# coding: utf-8

"""
    RIDB API

    The Recreation Information Database (RIDB) provides data resources to citizens, offering a single point of access to information about recreational opportunities nationwide. The RIDB represents an authoritative source of information and services for millions of visitors to federal lands, historic sites, museums, and other attractions/resources. This initiative integrates multiple Federal channels and sources about recreation opportunities into a one-stop, searchable database of recreational areas nationwide.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import recdotgov_client
from recdotgov_client.api.zones_api import ZonesApi  # noqa: E501
from recdotgov_client.rest import ApiException


class TestZonesApi(unittest.TestCase):
    """ZonesApi unit test stubs"""

    def setUp(self):
        self.api = ZonesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_permit_entrance_zone(self):
        """Test case for get_permit_entrance_zone

        Retrieve a zone for a permit entrance  # noqa: E501
        """
        pass

    def test_get_permit_entrance_zones(self):
        """Test case for get_permit_entrance_zones

        Retrieve all zones for a permit entrance  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
