# coding: utf-8

"""
    RIDB API

    The Recreation Information Database (RIDB) provides data resources to citizens, offering a single point of access to information about recreational opportunities nationwide. The RIDB represents an authoritative source of information and services for millions of visitors to federal lands, historic sites, museums, and other attractions/resources. This initiative integrates multiple Federal channels and sources about recreation opportunities into a one-stop, searchable database of recreational areas nationwide.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import recdotgov_client
from recdotgov_client.api.recreation_areas_api import RecreationAreasApi  # noqa: E501
from recdotgov_client.rest import ApiException


class TestRecreationAreasApi(unittest.TestCase):
    """RecreationAreasApi unit test stubs"""

    def setUp(self):
        self.api = RecreationAreasApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_organization_rec_area(self):
        """Test case for get_organization_rec_area

        Retrieve a specific RecArea by id for an organization  # noqa: E501
        """
        pass

    def test_get_organization_rec_areas(self):
        """Test case for get_organization_rec_areas

        Retrieve all RecAreas for an organization  # noqa: E501
        """
        pass

    def test_get_rec_area(self):
        """Test case for get_rec_area

        Retrieve a specific RecArea by id  # noqa: E501
        """
        pass

    def test_get_rec_areas(self):
        """Test case for get_rec_areas

        Retrieve all RecAreas  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
