# coding: utf-8

"""
    RIDB API

    The Recreation Information Database (RIDB) provides data resources to citizens, offering a single point of access to information about recreational opportunities nationwide. The RIDB represents an authoritative source of information and services for millions of visitors to federal lands, historic sites, museums, and other attractions/resources. This initiative integrates multiple Federal channels and sources about recreation opportunities into a one-stop, searchable database of recreational areas nationwide.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import recdotgov_client
from recdotgov_client.api.default_api import DefaultApi  # noqa: E501
from recdotgov_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_activity(self):
        """Test case for get_activity

        Retrieve a specific activity by id  # noqa: E501
        """
        pass

    def test_get_all_facility_media(self):
        """Test case for get_all_facility_media

        Retrieve all media for a facility  # noqa: E501
        """
        pass

    def test_get_all_rec_area_media(self):
        """Test case for get_all_rec_area_media

        Retrieve all media for a RecArea  # noqa: E501
        """
        pass

    def test_get_campsite(self):
        """Test case for get_campsite

        Retrieve a specific campsite by id  # noqa: E501
        """
        pass

    def test_get_event(self):
        """Test case for get_event

        Retrieve a specific event by id  # noqa: E501
        """
        pass

    def test_get_facility(self):
        """Test case for get_facility

        Retrieve a specific facility by id  # noqa: E501
        """
        pass

    def test_get_facility_activities(self):
        """Test case for get_facility_activities

        Retrieve all activities for a facility  # noqa: E501
        """
        pass

    def test_get_facility_activity(self):
        """Test case for get_facility_activity

        Retrieve a specific activity by id for a facility  # noqa: E501
        """
        pass

    def test_get_facility_address(self):
        """Test case for get_facility_address

        Retrieve a specific facility address by id  # noqa: E501
        """
        pass

    def test_get_facility_campsite(self):
        """Test case for get_facility_campsite

        Retrieve a specific campsite by id for a facility  # noqa: E501
        """
        pass

    def test_get_facility_campsites(self):
        """Test case for get_facility_campsites

        Retrieve all campsites for a facility  # noqa: E501
        """
        pass

    def test_get_facility_event(self):
        """Test case for get_facility_event

        Retrieve a specific event by id for a facility  # noqa: E501
        """
        pass

    def test_get_facility_events(self):
        """Test case for get_facility_events

        Retrieve all events for a facility  # noqa: E501
        """
        pass

    def test_get_facility_facility_address(self):
        """Test case for get_facility_facility_address

        Retrieve a specific facility address by id for a facility  # noqa: E501
        """
        pass

    def test_get_facility_facility_addresses(self):
        """Test case for get_facility_facility_addresses

        Retrieve all facility addresses for a facility  # noqa: E501
        """
        pass

    def test_get_facility_link(self):
        """Test case for get_facility_link

        Retrieve a specific link by id for a facility  # noqa: E501
        """
        pass

    def test_get_facility_links(self):
        """Test case for get_facility_links

        Retrieve all links for a facility  # noqa: E501
        """
        pass

    def test_get_facility_media(self):
        """Test case for get_facility_media

        Retrieve a specific media by id for a facility  # noqa: E501
        """
        pass

    def test_get_facility_permit_entrance(self):
        """Test case for get_facility_permit_entrance

        Retrieve a specific permit entrance by id for a facility  # noqa: E501
        """
        pass

    def test_get_facility_permit_entrances(self):
        """Test case for get_facility_permit_entrances

        Retrieve all permit entrances for a facility  # noqa: E501
        """
        pass

    def test_get_facility_tour(self):
        """Test case for get_facility_tour

        Retrieve a specific tour by id for a facility  # noqa: E501
        """
        pass

    def test_get_facility_tours(self):
        """Test case for get_facility_tours

        Retrieve all tours for a facility  # noqa: E501
        """
        pass

    def test_get_link(self):
        """Test case for get_link

        Retrieve a specific link by id  # noqa: E501
        """
        pass

    def test_get_media(self):
        """Test case for get_media

        Retrieve a specific media by id  # noqa: E501
        """
        pass

    def test_get_organization(self):
        """Test case for get_organization

        Retrieve a specific organization by id  # noqa: E501
        """
        pass

    def test_get_organization_facility(self):
        """Test case for get_organization_facility

        Retrieve a specific facility by id for an organization  # noqa: E501
        """
        pass

    def test_get_organization_rec_area(self):
        """Test case for get_organization_rec_area

        Retrieve a specific RecArea by id for an organization  # noqa: E501
        """
        pass

    def test_get_organization_rec_areas(self):
        """Test case for get_organization_rec_areas

        Retrieve all RecAreas for an organization  # noqa: E501
        """
        pass

    def test_get_permit_entrance(self):
        """Test case for get_permit_entrance

        Retrieve a specific permit entrance by id  # noqa: E501
        """
        pass

    def test_get_permit_entrance_attributes(self):
        """Test case for get_permit_entrance_attributes

        Retrieve all attributes for a permit entrance  # noqa: E501
        """
        pass

    def test_get_rec_area(self):
        """Test case for get_rec_area

        Retrieve a specific RecArea by id  # noqa: E501
        """
        pass

    def test_get_rec_area_activities(self):
        """Test case for get_rec_area_activities

        Retrieve all activities for a RecArea  # noqa: E501
        """
        pass

    def test_get_rec_area_activity(self):
        """Test case for get_rec_area_activity

        Retrieve a specific activity by id for a RecArea  # noqa: E501
        """
        pass

    def test_get_rec_area_address(self):
        """Test case for get_rec_area_address

        Retrieve a specific RecArea address by id  # noqa: E501
        """
        pass

    def test_get_rec_area_event(self):
        """Test case for get_rec_area_event

        Retrieve a specific event by id for a RecArea  # noqa: E501
        """
        pass

    def test_get_rec_area_events(self):
        """Test case for get_rec_area_events

        Retrieve all events for a RecArea  # noqa: E501
        """
        pass

    def test_get_rec_area_facility(self):
        """Test case for get_rec_area_facility

        Retrieve a specific facility by id for a RecArea  # noqa: E501
        """
        pass

    def test_get_rec_area_link(self):
        """Test case for get_rec_area_link

        Retrieve a specific link by id for a RecArea  # noqa: E501
        """
        pass

    def test_get_rec_area_links(self):
        """Test case for get_rec_area_links

        Retrieve all links for a RecArea  # noqa: E501
        """
        pass

    def test_get_rec_area_media(self):
        """Test case for get_rec_area_media

        Retrieve a specific media by id for a RecArea  # noqa: E501
        """
        pass

    def test_get_rec_area_rec_area_address(self):
        """Test case for get_rec_area_rec_area_address

        Retrieve a specific RecArea address by id for a RecArea  # noqa: E501
        """
        pass

    def test_get_rec_area_rec_area_addresses(self):
        """Test case for get_rec_area_rec_area_addresses

        Retrieve all RecArea addresses for a RecArea  # noqa: E501
        """
        pass

    def test_get_tour(self):
        """Test case for get_tour

        Retrieve a specific tour by id  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
