version: "3.9"
services:
    codegen:
        image:   swaggerapi/swagger-codegen-cli-v3
        volumes:
            - ${PWD}:/tmp/main
        command: "generate
             --input-spec /tmp/main/openapi.yaml \
             --lang python \
             --output /tmp/main/ \
             --config /tmp/main/.github/helpers/config.json"
