# coding: utf-8

"""
    RIDB API

    The Recreation Information Database (RIDB) provides data resources to citizens, offering a single point of access to information about recreational opportunities nationwide. The RIDB represents an authoritative source of information and services for millions of visitors to federal lands, historic sites, museums, and other attractions/resources. This initiative integrates multiple Federal channels and sources about recreation opportunities into a one-stop, searchable database of recreational areas nationwide.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse200METADATA(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'results': 'InlineResponse200METADATARESULTS',
        'parameters': 'InlineResponse200METADATAPARAMETERS'
    }

    attribute_map = {
        'results': 'RESULTS',
        'parameters': 'PARAMETERS'
    }

    def __init__(self, results=None, parameters=None):  # noqa: E501
        """InlineResponse200METADATA - a model defined in Swagger"""  # noqa: E501
        self._results = None
        self._parameters = None
        self.discriminator = None
        if results is not None:
            self.results = results
        if parameters is not None:
            self.parameters = parameters

    @property
    def results(self):
        """Gets the results of this InlineResponse200METADATA.  # noqa: E501


        :return: The results of this InlineResponse200METADATA.  # noqa: E501
        :rtype: InlineResponse200METADATARESULTS
        """
        return self._results

    @results.setter
    def results(self, results):
        """Sets the results of this InlineResponse200METADATA.


        :param results: The results of this InlineResponse200METADATA.  # noqa: E501
        :type: InlineResponse200METADATARESULTS
        """

        self._results = results

    @property
    def parameters(self):
        """Gets the parameters of this InlineResponse200METADATA.  # noqa: E501


        :return: The parameters of this InlineResponse200METADATA.  # noqa: E501
        :rtype: InlineResponse200METADATAPARAMETERS
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters):
        """Sets the parameters of this InlineResponse200METADATA.


        :param parameters: The parameters of this InlineResponse200METADATA.  # noqa: E501
        :type: InlineResponse200METADATAPARAMETERS
        """

        self._parameters = parameters

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200METADATA, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200METADATA):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
