# coding: utf-8

"""
    RIDB API

    The Recreation Information Database (RIDB) provides data resources to citizens, offering a single point of access to information about recreational opportunities nationwide. The RIDB represents an authoritative source of information and services for millions of visitors to federal lands, historic sites, museums, and other attractions/resources. This initiative integrates multiple Federal channels and sources about recreation opportunities into a one-stop, searchable database of recreational areas nationwide.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RecreationAreaFacility(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'facility_id': 'str',
        'facility_name': 'str'
    }

    attribute_map = {
        'facility_id': 'FacilityID',
        'facility_name': 'FacilityName'
    }

    def __init__(self, facility_id=None, facility_name=None):  # noqa: E501
        """RecreationAreaFacility - a model defined in Swagger"""  # noqa: E501
        self._facility_id = None
        self._facility_name = None
        self.discriminator = None
        self.facility_id = facility_id
        self.facility_name = facility_name

    @property
    def facility_id(self):
        """Gets the facility_id of this RecreationAreaFacility.  # noqa: E501

        RIDB unique Facility ID  # noqa: E501

        :return: The facility_id of this RecreationAreaFacility.  # noqa: E501
        :rtype: str
        """
        return self._facility_id

    @facility_id.setter
    def facility_id(self, facility_id):
        """Sets the facility_id of this RecreationAreaFacility.

        RIDB unique Facility ID  # noqa: E501

        :param facility_id: The facility_id of this RecreationAreaFacility.  # noqa: E501
        :type: str
        """
        if facility_id is None:
            raise ValueError("Invalid value for `facility_id`, must not be `None`")  # noqa: E501

        self._facility_id = facility_id

    @property
    def facility_name(self):
        """Gets the facility_name of this RecreationAreaFacility.  # noqa: E501

        Full name of the Facility  # noqa: E501

        :return: The facility_name of this RecreationAreaFacility.  # noqa: E501
        :rtype: str
        """
        return self._facility_name

    @facility_name.setter
    def facility_name(self, facility_name):
        """Sets the facility_name of this RecreationAreaFacility.

        Full name of the Facility  # noqa: E501

        :param facility_name: The facility_name of this RecreationAreaFacility.  # noqa: E501
        :type: str
        """
        if facility_name is None:
            raise ValueError("Invalid value for `facility_name`, must not be `None`")  # noqa: E501

        self._facility_name = facility_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RecreationAreaFacility, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RecreationAreaFacility):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
