name: ridb-client-automation

on:

    push:
        branches: [ "main" ]
        paths:
            - ".github/**"
    schedule:
        -   cron: "0 4 * * 6"

jobs:

    test-suite:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                include:
                    #  - { name: 'Python 3.10', python: '3.10', tox: py310 }
                    - { name: 'Python 3.9', python: '3.9', tox: py39 }
                    - { name: 'Python 3.8', python: '3.8', tox: py38 }
                    - { name: 'Python 3.7', python: '3.7', tox: py37 }
                    - { name: 'Python 3.6', python: '3.6', tox: py36 }
        steps:
            -   name: Set up Github Workspace
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   name: Set up Python Environment ${{ matrix.python }}
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python }}
            -   name: Install Test Dependencies
                run:  |
                      python -m pip install --upgrade pip wheel
                      python -m pip install tox
            -   name: Tox Test Suite
                run:  |
                      tox -e ${{ matrix.tox }}

    code-gen:
        runs-on: ubuntu-latest
        needs:   test-suite
        outputs:
            release: ${{ steps.commit.outputs.release }}
        steps:
            -   name: Checkout Latest Changes
                uses: actions/checkout@v2
                with:
                    path:        ${{ github.workspace }}/latest
                    ref:         ${{ github.ref }}
                    fetch-depth: 0
            -   name: Checkout Destination Branch
                uses: actions/checkout@v2
                with:
                    path:        ${{ github.workspace }}/main
                    ref:         main
                    fetch-depth: 0
            -   name: Set up Python Environment
                uses: actions/setup-python@v2
                with:
                    python-version: 3.9
            -   name: Install Dependencies
                run:  |
                      python -m pip install isort black requests packaging
            -   name:              Setup Git Config
                working-directory: ${{ github.workspace }}/main
                run:               |
                                   git config --global user.name "github-actions[bot]"
                                   git config --global user.email "github-actions[bot]@users.noreply.github.com"
            -   name:              Bring In Changes
                working-directory: ${{ github.workspace }}/main
                run:               |
                                   git rm -rf ${{ github.workspace }}/main/ || true
                                   mkdir -p ${{ github.workspace }}/main/.github
                                   cp -a ${{ github.workspace }}/latest/.github/. ${{ github.workspace }}/main/.github/
            -   name:              Generate All Code
                working-directory: ${{ github.workspace }}/main
                run:               |
                                   python ${{ github.workspace }}/main/.github/helpers/generate_spec.py
                                   docker-compose --file ${{ github.workspace }}/main/.github/helpers/docker-compose.yaml run codegen
            -   name:              Prepare Changes
                working-directory: ${{ github.workspace }}/main
                run:               |
                                   git checkout -b ${{ github.run_id }}
                                   sudo chown -R "$(id -u)" ${{ github.workspace }}/main
                                   cp ${{ github.workspace }}/latest/.gitignore ${{ github.workspace }}/main/.gitignore
                                   cp ${{ github.workspace }}/latest/LICENSE ${{ github.workspace }}/main/LICENSE
            -   name:              Format Code
                working-directory: ${{ github.workspace }}/main
                run:               |
                                   isort --profile black ${{ github.workspace }}/main
                                   black ${{ github.workspace }}/main
            -   name:              Find File Paths Changed
                id:                diff
                working-directory: ${{ github.workspace }}/main
                run:               |
                                   echo ::set-output name=diff::$(git diff --name-only origin/main)
                                   echo PROJECT_RELEASE="false" >> ${GITHUB_ENV}
            -   name: Enable New Release
                if:   |
                      Contains(steps.diff.outputs.diff, 'recdotgov_client/') ||
                        Contains(steps.diff.outputs.diff, 'docs/') ||
                        Contains(steps.diff.outputs.diff, 'tests/') ||
                        Contains(steps.diff.outputs.diff, '.github/')
                run:  |
                      echo PROJECT_RELEASE="true" >> ${GITHUB_ENV}
            -   name:              Increment Version Number
                if:                ${{ env.PRROJECT_RELEASE }} == "true"
                working-directory: ${{ github.workspace }}/main
                run:               |
                                   echo PROJECT_VERSION=$(python .github/helpers/packaging_increment.py --increment patch) >> ${GITHUB_ENV}
                                   NEW_CONFIG=$(cat .github/helpers/config.json | jq '.packageVersion = "${{ env.PROJECT_VERSION }}"')
                                   echo ${NEW_CONFIG} > .github/helpers/config.json
            -   name:              Commit Changes
                id:                commit
                working-directory: ${{ github.workspace }}/main
                run:               |
                                   git add ${{ github.workspace }}/main/
                                   git commit -m "CodeGen - ${{ github.run_id }}"
                                   git push --set-upstream origin ${{ github.run_id }}
                                   git checkout main
                                   git merge ${{ github.run_id }}
                                   git push origin main --force
                                   git branch -d ${{ github.run_id }}
                                   git fetch -p
                                   echo ::set-output name=release::${{ env.PROJECT_RELEASE }}

    release:
        runs-on: ubuntu-latest
        needs:   code-gen
        if:      ${{needs.code-gen.outputs.release}} == "true"
        steps:
            -   name: Set up Github Workspace
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   name: Set up Python Environment
                uses: actions/setup-python@v2
                with:
                    python-version: 3.9
            -   name: Version Incrementer
                run:  |
                      python -m pip install packaging
            -   name: Version Fetcher
                run:  |
                      echo PROJECT_NAME=$(python setup.py --name) >> ${GITHUB_ENV}
                      echo PROJECT_VERSION=$(python .github/helpers/packaging_increment.py) >> ${GITHUB_ENV}
            -   name: Tag Setter
                run:  |
                      echo PROJECT_TAG='v${{ env.PROJECT_VERSION }}' >> ${GITHUB_ENV}
                      echo PROJECT_RELEASE='${{ env.PROJECT_NAME }} v${{ env.PROJECT_VERSION }}' >> ${GITHUB_ENV}
            -   name: Draft a Release
                uses: release-drafter/release-drafter@v5
                with:
                    config-name: release-drafter.yml
                    name:        ${{ env.PROJECT_RELEASE }}
                    version:     ${{ env.PROJECT_VERSION }}
                    tag:         ${{ env.PROJECT_TAG }}
                    publish:     true
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    github-pages-publish:
        runs-on: ubuntu-latest
        needs:   release
        steps:
            -   name: Checkout Latest Changes
                uses: actions/checkout@v2
                with:
                    path:        ${{ github.workspace }}/main
                    ref:         ${{ github.ref }}
                    fetch-depth: 0
            -   name: Checkout gh-pages Branch
                uses: actions/checkout@v2
                with:
                    path:        ${{ github.workspace }}/gh-pages
                    ref:         gh-pages
                    fetch-depth: 0

            -   name: Setup Git Config
                run:  |
                      git config --global user.name "github-actions[bot]"
                      git config --global user.email "github-actions[bot]@users.noreply.github.com"
            -   name:              Get Commit SHA from main
                working-directory: ${{ github.workspace }}/main
                run:               |
                                   COMMIT_SHA=$(git rev-parse HEAD)
                                   echo "COMMIT_SHA=${COMMIT_SHA}" >> ${GITHUB_ENV}
            -   name:              Commit Changes to gh-pages Branch
                working-directory: ${{ github.workspace }}/gh-pages
                run:               |
                                   git rm -rf . || true
                                   rm -rf ${{ github.workspace }}/main/.git/
                                   cp -a ${{ github.workspace }}/main/. ${{ github.workspace }}/gh-pages/
                                   git add .
                                   git diff-index --quiet HEAD || git commit -m "GitHub Pages - ${{ env.COMMIT_SHA }}"
                                   git push origin gh-pages --force
